<?php $this->headTitle($this->translate('Overview')) ?>

<div class="row">
    <div class="col-md-12">
        <h1 class="h1"><?php echo $this->translate('Overview') ?></h1>
    </div>
</div>
<div class="row">

    <div class="col-md-4">
        <nav class="nav">
            <ul class="list-group">
                <li class="list-group-item active"><span class="glyphicon glyphicon-home"></span> <?php echo $this->translate('Overview') ?></li>
                <li class="list-group-item"><a href="<?php echo $this->url('dashboard/contacts') ?>"><span class="glyphicon glyphicon-user"></span> <?php echo $this->translate('Contacts') ?></a></li>
            </ul>
        </nav>
    </div>

    <div class="col-md-8">


    </div>

</div>
