<?php $this->headTitle($this->translate('Overview')) ?>

<div class="row">
    <div class="col-md-12">
        <h1 class="h1"><?php echo $this->translate('Overview') ?></h1>
    </div>
</div>
<div class="row">

    <div class="col-md-4">
        <nav class="nav">
            <ul class="list-group">
                <li class="list-group-item active"><span class="glyphicon glyphicon-home"></span> <?php echo $this->translate('Overview') ?></li>
                <li class="list-group-item"><span class="glyphicon glyphicon-user"></span> <?php echo $this->translate('Contacts') ?></li>
            </ul>
        </nav>
    </div>

    <div class="col-md-8">

        <table class="table">
            <tr>
                <th><?php echo $this->translate('First name') ?></th>
                <th><?php echo $this->translate('Last name') ?></th>
                <th><?php echo $this->translate('E-mail address') ?></th>
            </tr>
            <?php foreach ($this->contacts as $contact): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($contact->getFirstName()) ?></td>
                    <td><?php echo $this->escapeHtml($contact->getLastName()) ?></td>
                    <td><?php echo $this->escapeHtml('') ?></td>
                </tr>
            <?php endforeach ?>
        </table>
    </div>

</div>
