<?php $this->headTitle($this->translate('Add a new contact')) ?>

<div class="row">
    <div class="col-md-12">
        <h1 class="h1"><?php echo $this->translate('Add a new contact') ?></h1>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
<?php
    $form->setAttribute('action', $this->url('contact', ['action' => 'add']));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('contact_id'));
    echo $this->formRow($form->get('first_name'));
    echo $this->formRow($form->get('last_name'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
?>
    </div>
</div>
