<?php $this->headTitle($this->translate('Add a new contact')) ?>

<div class="row">
    <div class="col-md-12">
        <h1 class="h1"><?php echo $this->translate('Add a new contact') ?></h1>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <?php
        // This provides a default CSS class and placeholder text for the title element:
        $firstName = $form->get('first_name');
        $firstName->setAttribute('class', 'form-control');
        $firstName->setAttribute('placeholder', $this->translate('First name'));

        // This provides a default CSS class and placeholder text for the artist element:
        $lastName = $form->get('last_name');
        $lastName->setAttribute('class', 'form-control');
        $lastName->setAttribute('placeholder', $this->translate('Last name'));

        // This provides CSS classes for the submit button:
        $submit = $form->get('submit');
        $submit->setAttribute('class', 'btn btn-primary');

        $form->setAttribute('action', $this->url('contact', ['action' => 'add']));
        $form->prepare();

        echo $this->form()->openTag($form);
        ?>

    <div class="form-group">
        <?php echo $this->formLabel($firstName, $this->translate('First name')) ?>
        <?php echo $this->formElement($firstName) ?>
        <?php echo $this->formElementErrors()->render($firstName, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?php echo $this->formLabel($lastName, $this->translate('Last name')) ?>
        <?php echo $this->formElement($lastName) ?>
        <?php echo $this->formElementErrors()->render($lastName, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?php echo $this->formSubmit($submit); ?>
        <a class="btn btn-default" href="<?php echo $this->url('contact') ?>"><?php echo $this->translate('Cancel') ?></a>
    </div>

    <?php
        echo $this->formHidden($form->get('contact_id'));
        echo $this->form()->closeTag();
    ?>
    </div>
</div>
