<?php $this->headTitle($this->translate('Detail of contact')) ?>

<div class="row">
    <div class="col-md-12">
        <h1 class="h1"><?php echo $this->translate('Detail of contact') ?></h1>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
    </div>
    <div class="col-md-8"
        <ul class="list-group">
            <li class="list-group-item"><strong>First name:</strong> <?php echo $this->escapeHtml($this->contact->getFirstName()) ?></li>
            <li class="list-group-item"><strong>Last name:</strong> <?php echo $this->escapeHtml($this->contact->getLastName()) ?></li>
        </ul>
        <br>
        <h2 class="h2">Email addresses</h2>
        <ul class="list-group">
            <?php foreach ($this->contactEmails as $contactEmail): ?>
                <li class="list-group-item"><?php echo $this->escapeHtml($contactEmail->getEmailAddress()) ?></li>
            <?php endforeach ?>
        </ul>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <a href="<?php echo $this->url('contact') ?>" class="btn btn-default"><span class="glyphicon glyphicon-arrow-left"></span> Back to list</a>
    </div>
</div>