<?php $this->headTitle($this->translate('Overview of contacts')) ?>

<div class="row">
    <div class="col-md-12">
        <h1 class="h1"><?php echo $this->translate('Overview of contacts') ?></h1>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th><a href="<?php echo $this->url('contact/add') ?>"><?php echo $this->translate('Add') ?></a></th>
            </tr>

            <?php foreach ($this->contacts as $contact): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($contact->getFirstName()) ?></td>
                    <td><?php echo $this->escapeHtml($contact->getLastName()) ?></td>
                    <td>
                        <a href="<?php echo $this->url('contact/edit', ['id' => $contact->getContactId()]) ?>"><?php echo $this->translate('Edit') ?></a>
                        <a href="<?php echo $this->url('contact/delete', ['id' => $contact->getContactId()]) ?>"><?php echo $this->translate('Delete') ?></a>
                    </td>
                </tr>
            <?php endforeach ?>
        </table>
    </div>
</div>
