<?php echo $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->escapeHtml(Application\Module::APP_NAME))->setSeparator(' | ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->appendStylesheet($this->basePath('css/bootstrap.min.css'))
            ->appendStylesheet($this->basePath('css/font-awesome.min.css'))
            ->appendStylesheet($this->basePath('css/bootstrap-social.css'))
            ->appendStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->appendStylesheet($this->basePath('css/style.css'))
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript() ?>
    </head>
    <body>
        <section id="top" name="top"><a name="top"></a>
            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <div name="top" class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand smoothScroll" href="<?php echo $this->url('home', [], ['fragment' => 'top']) ?>">
                            <img src="<?php echo $this->basePath('img/cloudcrm-logo.svg') ?>" height="28" width="28" alt="<?php echo $this->escapeHtml(Application\Module::APP_NAME)?> <?php echo \Application\Module::VERSION ?>"/>&nbsp;<?php echo $this->escapeHtml(Application\Module::APP_NAME) ?>
                        </a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li><a class="navbar-link smoothScroll" id="link-intro" href="<?php echo $this->url('home', [], ['fragment' => 'intro']) ?>"><?php echo $this->translate('Introduction') ?></a></li>
                            <li><a class="navbar-link smoothScroll" id="link-features" href="<?php echo $this->url('home', [], ['fragment' => 'features']) ?>"><?php echo $this->translate('Features') ?></a></li>
                            <li><a class="navbar-link smoothScroll" id="link-recommendations" href="<?php echo $this->url('home', [], ['fragment' => 'recommendations']) ?>"><?php echo $this->translate('Recommendations') ?></a></li>
                            <li><a class="navbar-link smoothScroll" id="link-pricing" href="<?php echo $this->url('home', [], ['fragment' => 'pricing']) ?>"><?php echo $this->translate('Pricing') ?></a></li>
                            <li><a class="navbar-link smoothScroll" id="link-contact" href="<?php echo $this->url('home', [], ['fragment' => 'contact']) ?>"><?php echo $this->translate('Contact') ?></a></li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li><a class="navbar-link" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Register') ?></a></li>
                            <li><a class="navbar-link" href="<?php echo $this->url('auth') ?>"><?php echo $this->translate('Login') ?></a></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </section>

        <div class="content-block">
        <?php 
        $url = 'http://' . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'];
        if (strpos($url,'dashboard') !== false)
         {
            $htmlNavDashboard =  "
                 <div class='col-md-4'>
                    <nav class='nav'>
                        <ul class='list-group'>
                            <li class='list-group-item active'><span class='glyphicon glyphicon-home'></span>" 
                            .  $this->translate('Overview') 
                            ."</li>
                            <li class='list-group-item'><a href='".
                              $this->url('dashboard/contacts').
                              "'><span class='glyphicon glyphicon-user'></span>".
                              $this->translate('Contacts') 
                             . "</a></li>
                            <li class='list-group-item'><a href='   '><i class='fa fa-building-o' aria-hidden='true'></i>  Companies</a></li> 
                       </ul>
                    </nav>
                </div>  
            ";
            echo $htmlNavDashboard;
        }
         

         echo $this->content ?>

        </div>

        <div class="container">
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by <a href="https://www.in2it.be/" title="In2it VOF" target="_blank">in2it V.O.F.</a>. All rights reserved.</p>
            </footer>
        </div>
        <?php
            echo $this->inlineScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </body>
</html>
