<?php echo $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF-CRM')->setSeparator(' | ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->appendStylesheet($this->basePath('css/bootstrap.min.css'))
            ->appendStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->appendStylesheet($this->basePath('css/style.css'))
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript() ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                        <img src="<?php echo $this->basePath('img/zf-logo-mark.svg') ?>" height="28" alt="ZF-CRM <?php echo \Application\Module::VERSION ?>"/>&nbsp;ZF-CRM
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home') ?>">Home</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by <a href="https://www.in2it.be/" title="In2it VOF" target="_blank">in2it V.O.F.</a>. All rights reserved.</p>
            </footer>
        </div>
        <?php
            echo $this->inlineScript()
                ->appendFile($this->basePath('js/jquery-3.1.0.min.js'))
                ->appendFile($this->basePath('js/bootstrap.min.js'))
        ?>
    </body>
</html>
