<?php $this->headTitle($this->translate('You cancelled the authentication')) ?>

<div class="row">
    <div class="col-md-12">
        <h1 class="h1"><?php echo $this->translate('You cancelled the authentication') ?></h1>
        <p>
            <?php echo sprintf(
                $this->translate('We have detected you cancelled the authentication process. %s if you believe this was done by mistake.'),
                '<a href="' . $this->url('auth') . '" title="' . $this->translate('Go to login') . '">' . $this->translate('Go to login') . '</a>'
            ) ?>
        </p>
    </div>
</div>
