<?php $this->headTitle($this->translate('Please authenticate yourself')) ?>

<div class="row">
    <div class="col-md-12">
        <h1 class="h1"><?php echo $this->translate('Please authenticate yourself') ?></h1>
    </div>
</div>

<div class="row">
    <div class="col-md-3">&nbsp;</div>
    <div class="col-md-6">
        <a class="btn btn-linkedin">Login with LinkedIn</a>
    </div>
    <div class="col-md-3">&nbsp;</div>
</div>
