<?php
$form = $this->form;
$contactFieldset = $form->get('contact-fieldset');

// This provides a default CSS class and placeholder text for the title element:
$firstName = $contactFieldset->get('first_name');
$firstName->setAttribute('class', 'form-control');
$firstName->setAttribute('placeholder', $this->translate('First name'));

// This provides a default CSS class and placeholder text for the artist element:
$lastName = $contactFieldset->get('last_name');
$lastName->setAttribute('class', 'form-control');
$lastName->setAttribute('placeholder', $this->translate('Last name'));

$csrf = $form->get('csrf');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setValue($this->submitLabel);
$submit->setAttribute('class', 'btn btn-primary');

$form->prepare();

echo $this->form()->openTag($form);
?>

    <div class="form-group">
        <?php echo $this->formLabel($firstName, $this->translate('First name')) ?>
        <?php echo $this->formElement($firstName) ?>
        <?php echo $this->formElementErrors()->render($firstName, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?php echo $this->formLabel($lastName, $this->translate('Last name')) ?>
        <?php echo $this->formElement($lastName) ?>
        <?php echo $this->formElementErrors()->render($lastName, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?php echo $this->formSubmit($submit); ?>
        <a class="btn btn-default" href="<?php echo $this->url('contact') ?>"><?php echo $this->translate('Cancel') ?></a>
    </div>

<?php
echo $this->formHidden($contactFieldset->get('contact_id'));
echo $this->formHidden($form->get('csrf'));
echo $this->form()->closeTag();
?>