<?php $this->headTitle(sprintf($this->translate('Delete %s %s?'), $contact->getFirstName(), $contact->getLastName())) ?>

<div class="row">
    <div class="col-md-12">
        <h1 class="h1"><?php echo sprintf($this->translate('Delete %s %s?'), $contact->getFirstName(), $contact->getLastName()) ?></h1>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <p>
            Are you sure that you want to delete
            "<?php echo $this->escapeHtml($contact->getFirstName()) ?>
            <?php echo $this->escapeHtml($contact->getLastName()) ?>" ?
        </p>

        <form action="<?php echo $this->url('contact/delete', ['id' => $contact->getContactId()]) ?>" method="post">
            <div class="form-group">
                <input type="hidden" name="id" value="<?php echo (int) $contact->getContactId() ?>" />
                <input type="submit" class="btn btn-danger" name="del" value="Yes" />
                <input type="submit" class="btn btn-success" name="del" value="No" />
            </div>
        </form>
    </div>
</div>